### ISSUE TITLE
Can the namedmanager work normally in  Centos 7?

### ISSUE THREAD

**Issue by fengtianya** [jethrocarr/namedmanager#52]
I installerd namedmanager in Centos 7 with bind-chroot-9.9.4-38.el7_3.2.x86_64,and namedmanager generated zonefiles,but the domain name server was still not normal, also i shutted down the firewall and SELinux, and the namedmanager can be synchronized。
In addition, if do not install namedmanager, only use bind-chroot, write the zonefile by myself, DNS service is normal.
    so， I want to know  anbody in centos7 to install the namedmanager whether it can work nomarlly?

**Comment by frankcrawford** [comment]
@fengtianya what issues are you seeing?  I have it installed on CentOS 7.2 server with bind-chroot setup and don't have any issues.

**Comment by fengtianya** [comment]
The problem I encountered was that namedmanager was unable to synchronize, unable to generate zone file. The experimental environment is centos7.2 and MySQL 5.7 and bind-chroot. But tonight I can solve this problem, a key step to solve is to restart the named-chroot service before entering the namedmanger management platform, add host and domain name and A records, and then restart your named-chroot.
Also note that the namedmanger 1.9 in MySQL 5.7 installation when the database is wrong, this is because the MySQL's validate_password plugin is installed by default. This will require that passwords contain at least one upper case letter, one lower case letter, one digit, and one special character, and that the total password length is at least 8 charactersand .But the namedmanager install's script ./autoinstall default  password is randomly  10 characters, so, it need to by modified.

**Comment by fengtianya** [comment]
英文写完了，写点中文吧，不知道有没有chinese friend 看到，我碰到的问题是在centos7.2下，安装namedmanager1.9，同时安装了mysql 5.7 最新版本，但是发现在namedmanager无法同步生成区域文件，后台显示黄色，而不是绿色，这就是不正常。后来解决了这个问题，发现时我缺少关键的一步，在进入控制台之前重启一下named-chroot服务和进入控制台之后再重启一下named-chroot服务（这一步可能不是很重要）。
值得注意的是，namedmanager脚本/usr/share/namedmanager/resources/autoinstall.pl 需要修改里面默认的my $db_bs_password     = random_password(10)这一项，因为与mysql 5.7 密码策略不符，导致无法生成namedmanager配置文件，最后也无法连接数据库。
修改密码为固定密码吧，大小写字母，数字，特殊符号，至少8位，修改后，重新执行脚本，忽略mysql错误就可以了。

**Comment by hylitjob** [comment]
我在centos 7下安装全套服务，运行ok啦。  因为php soap模块没安装的缘故造成通信失败，都解决啦！

**Comment by hylitjob** [comment]
我dns服务器是bind

**Comment by ask870** [comment]
SOAP API这部分有没有使用样例，我想通过程序往namedmananger里面自动增删改记录

**Comment by waitspring** [comment]
各位，如果上 NamedManager 的 Named Servers 频道配置 DNS 主机之后，一直显示 `status_unsynced`，且主机日志报错为

```
PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://dns.test.jr-zbj.com/namedexample/api/namedmanager.wsdl' : failed to load external entity "http://dns.test.jr-zbj.com/namedexample/api/namedmanager.wsdl"
 in /usr/share/namedmanager/bind/include/application/inc_soap_api.php on line 33
PHP Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://dns.test.jr-zbj.com/namedexample/api/namedmanager.wsdl' : failed to load external entity "http://dns.test.jr-zbj.com/namedexample/api/namedmanager.wsdl"
 in /usr/share/namedmanager/bind/include/application/inc_soap_api.php:33
Stack trace:
#0 /usr/share/namedmanager/bind/include/application/inc_soap_api.php(33): SoapClient->SoapClient('http://dns.test...')
#1 /usr/share/namedmanager/bind/namedmanager_bind_configwriter.php(108): soap_api->authenticate()
#2 {main}
  thrown in /usr/share/namedmanager/bind/include/application/inc_soap_api.php on line 33
```

那么，这种问题该如何处理？

**Comment by daliugit** [comment]
@waitspring 我也遇到了这种问题，请问你最后有找到解决办法吗

**Comment by fengtianya** [comment]
好多年了，三年了，注意看文档，有一条专门检查配置文件的命令的，这是一条关键命令，出错就是配置文件多了标点，不合格符号，打错英文了等等，用这条命令检查一下配置文件，如果不报错，就可以了。之前没注意，后来看到这条命令就可以了。发自我的iPhone------------------ Original ------------------From: daliugit  <notifications@github.com>Date: Fri,Dec 18,2020 4:48 PMTo: jethrocarr/namedmanager <namedmanager@noreply.github.com>Cc: fengtianya <tawegu@126.com>, Mention <mention@noreply.github.com>Subject: Re: [jethrocarr/namedmanager] Can the namedmanager work normally in Centos 7? (#52)
@waitspring 我也遇到了这种问题，请问你最后有找到解决办法吗

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jethrocarr/namedmanager/issues/52#issuecomment-747951828",
"url": "https://github.com/jethrocarr/namedmanager/issues/52#issuecomment-747951828",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lujay** [comment]
> Couldn't load from 'http://dns.test.jr-zbj.com/namedexample/api/namedmanager.wsdl

Couldn't load from 'http://dns.test.jr-zbj.com/namedexample/api/namedmanager.wsdl  这个路径错了，应该是 你看看是不是
![image](https://user-images.githubusercontent.com/6263244/151349387-e5dca9c9-4c06-44a4-996c-989182ae87b8.png)

![image](https://user-images.githubusercontent.com/6263244/151349329-6453ebf8-909e-4024-b661-29ac3720bbbb.png)
