### ISSUE TITLE
PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 

### ISSUE THREAD

**Issue by hylitjob** [jethrocarr/namedmanager#58]
I can download the wsdl file through webbrowser, but run the follow comand, it raise issues
php  /usr/local/download/namedmanager/bind/namedmanager_bind_configwriter.php 

PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://10.0.21.78/namedmanager/api/namedmanager.wsdl' : failed to load external entity "https://10.0.21.78/namedmanager/api/namedmanager.wsdl"
 in /usr/local/download/namedmanager/bind/include/application/inc_soap_api.php on line 33
PHP Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://10.0.21.78/namedmanager/api/namedmanager.wsdl' : failed to load external entity "https://10.0.21.78/namedmanager/api/namedmanager.wsdl"
 in /usr/local/download/namedmanager/bind/include/application/inc_soap_api.php:33
Stack trace:
#0 /usr/local/download/namedmanager/bind/include/application/inc_soap_api.php(33): SoapClient->SoapClient('https://10.0.21...')
#1 /usr/local/download/namedmanager/bind/namedmanager_bind_configwriter.php(108): soap_api->authenticate()
#2 {main}
  thrown in /usr/local/download/namedmanager/bind/include/application/inc_soap_api.php on line 33

**Comment by hylitjob** [comment]
it works with http protocol
